fix: prevent overwriting hot repository on init (#353)
This commit ensures that the hot repository won't get overwritten during
init when the non-hot repository does not exist.

---

**Motivation:** During my setup of rustic, I used a bad cold repository
reference by mistake. This led rustic to corrupt my hot repository,
which I thought it should have prevented. I guess there may be other
places we'd want to detect and safeguard against hot/cold
inconsistencies, but I've not encountered them and I'm not proficient
enough with the codebase yet to go with a broader change confidently.

**Old behavior:**

```console
$ --repo ./cold --repo-hot ./hot --password 'rustic' init
[INFO] using no config file, none of these exist: /home/myself/.config/rustic/rustic.toml, /etc/rustic/rustic.toml, ./rustic.toml
[INFO] key 70fde4b5 successfully added.
[INFO] repository 7e37c018 successfully created.
[INFO] using cache at /home/myself/.cache/rustic/7e37c0182ecf9122ac29094aba7a2456e2f4fcd8901de5548ba8d1f2cfbf424e

$ sha256sum hot/config
af78a9385084d3734fe4bba280449266c0a151ab6390baf6b684122e09f76c2a  hot/config

$ rustic --repo ./cold2 --repo-hot ./hot --password 'rustic' init
[INFO] using no config file, none of these exist: /home/myself/.config/rustic/rustic.toml, /etc/rustic/rustic.toml, ./rustic.toml
[INFO] key 7455ca1b successfully added.
[INFO] repository f6b5c80d successfully created.
[INFO] using cache at /home/myself/.cache/rustic/f6b5c80d9aea1e279cb76f7f3855d563f277fa43884300738fe957a8051c54ff

$ sha256sum hot/config
28a41dfbc7653c4f2aea443a94bfc5a665d120969bd38ccf663f6f1da505d7a0  hot/config
```

New behavior:

```console
$ rustic --repo ./cold --repo-hot ./hot --password 'rustic' init
[INFO] using no config file, none of these exist: /home/myself/.config/rustic/rustic.toml, /etc/rustic/rustic.toml, ./rustic.toml
[INFO] key 60190cbb successfully added.
[INFO] repository e5ce7241 successfully created.
[INFO] using cache at /home/myself/.cache/rustic/e5ce7241a24254e7719865d60db0f0a939a5cdc21e1be9176856e5d385d70dfc

$ rustic --repo ./cold2 --repo-hot ./hot --password 'rustic' init
[INFO] using no config file, none of these exist: /home/myself/.config/rustic/rustic.toml, /etc/rustic/rustic.toml, ./rustic.toml
error: Config file already exists. Aborting.
```

Co-authored-by: aawsome <37850842+aawsome@users.noreply.github.com>